language: php
branches:
  only:
  - master
  - "/^.*[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+.*$/"
php:
- '7.2'
script: phpunit --bootstrap src/stub.php --test-suffix '-test.php,Test.php,.phpt'
  tests
notifications:
  email: false
before_deploy:
- composer phar:install-tools
- composer install --prefer-dist --no-dev --no-interaction
- php box.phar build
deploy:
  provider: releases
  skip_cleanup: 'true'
  file: php-hook.phar
  api_key:
    secure: qKOHrZmyF6AhD0AXud7AkJl97UoY8tv5qBf3i9eTZHBe6XmO51Q6U8sgChik6xIefylSKn0Cy6QCiGBEdWt/2cl/TOSD1EPr6NpnSpZCXzB/YlXa0jU5NR5ZoDzk93n1fo4syAPgM6J7xQiZrG6rRj14dZkEInm1XSzyPZbL53VSbXuVYDCOlOYsFXBm4iuhFhNXtY9ePxacLSEi2Pu5PRbQH8xYOjyUeovd8zzs1ksHO/+9eA4OXbb2MzqObhv3MAcktU9ywHiMvWZ5E1yVdzryBrhBSwZSu90fo5wYoEzFspsLB3OSDsr6f50o/EXsCnVcxk64E0c9wkg7T3xe5fL07rlQ8Dc4vsllbzp0UOHuGb1N2xuJ670kjS0vxpCtu30NMDT3jn/Ztf6dq4nIuP9iqZxnlmLkznlu7mF8+qxBfelXKhN3cutjRNfb6UZae9EwmOzXbAShLVmi8mYB3fRPPgfFsZI52+i/Pka+X7oCeBIzZm0tg3NC4CgafPRWqji5NPf9VmWch4vlHxOBYMXKq4mt/fnvEU7S/sraYWWW40SteMezgmUuLz4p8UxxUoqgTw/qIWNDPID9UPqDxsYUeRbbn6QVXiKIG23/1rmjv+Gr5mTYo5WXTiPPI+Npun6ePqRAK7P1WSdoX5nwcveeNH2Y8A7C2Sckfvfffug=
  on:
    repo: bhoogter/php-hook
    tags: true
